services:
  db:
    image: postgres:15
    container_name: hr_ai_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hr_ai_chatbot
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: hr_ai_app
    restart: always
    ports:
      - "4568:4567"
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - db

volumes:
  pgdata:
